<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Zend\Permissions\Acl\Assertion\AssertionInterface'                  => __DIR__ . '/Assertion/AssertionInterface.php',
  'Zend\Permissions\Acl\Assertion\AssertionManager'                    => __DIR__ . '/Assertion/AssertionManager.php',
  'Zend\Permissions\Acl\Assertion\Exception\InvalidAssertionException' => __DIR__ . '/Assertion/Exception/InvalidAssertionException.php',
  'Zend\Permissions\Acl\Assertion\AssertionAggregate'                  => __DIR__ . '/Assertion/AssertionAggregate.php',
  'Zend\Permissions\Acl\Acl'                                           => __DIR__ . '/Acl.php',
  'Zend\Permissions\Acl\Role\GenericRole'                              => __DIR__ . '/Role/GenericRole.php',
  'Zend\Permissions\Acl\Role\RoleInterface'                            => __DIR__ . '/Role/RoleInterface.php',
  'Zend\Permissions\Acl\Role\Registry'                                 => __DIR__ . '/Role/Registry.php',
  'Zend\Permissions\Acl\AclInterface'                                  => __DIR__ . '/AclInterface.php',
  'Zend\Permissions\Acl\Resource\ResourceInterface'                    => __DIR__ . '/Resource/ResourceInterface.php',
  'Zend\Permissions\Acl\Resource\GenericResource'                      => __DIR__ . '/Resource/GenericResource.php',
  'Zend\Permissions\Acl\Exception\ExceptionInterface'                  => __DIR__ . '/Exception/ExceptionInterface.php',
  'Zend\Permissions\Acl\Exception\RuntimeException'                    => __DIR__ . '/Exception/RuntimeException.php',
  'Zend\Permissions\Acl\Exception\InvalidArgumentException'            => __DIR__ . '/Exception/InvalidArgumentException.php',
);
